### ISSUE TITLE
Haversine will not import with Ubuntu 20.04 and Python 3.8.2

### ISSUE THREAD

**Issue by gloorfindel** [mapado/haversine#32]
Currently running Python 3.8.2 on Ubuntu 20.04 and receive the following error when attempting to use haversine:
```Traceback (most recent call last):
 line 1, in <module>
    from haversine import haversine, Unit
ImportError: cannot import name 'haversine' from 'haversine' (unknown location)```

**Comment by RomainMapado** [comment]
Import seems to work with Python 3.8.2


```
Python 3.8.2 (default, May  4 2020, 15:53:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from haversine import haversine, Unit
>>> lyon = (45.7597, 4.8422) 
>>> paris = (48.8567, 2.3508)
>>> haversine(lyon, paris)
392.2172595594006
```


Did you install the latest haversine version (2.2.0) ?

**Comment by gloorfindel** [comment]
Thanks for getting back. 

Was actually an issue with Intellij. When I hovered over the `haversine, Unit` portion in the code, it asked if I wanted to import it. After selecting `Import`, it imported and was able to run.
